### PR TITLE
Added example for player name

### PR DESCRIPTION
**Pull request by greavettey**
I also added line breaks in a couple files because they should be there, and reworded an error message to be clearer.

### CODE REVIEW

**Review by louis-bompart — APPROVED** [review]
Great jobs thanks!
@all-contributors please add @axelgreavette for code

**Comment by louis-bompart** [comment]
Great stuff @axelgreavette !
@all-contributors please add @axelgreavette for code

**Review by louis-bompart — CHANGES_REQUESTED** [review]
One change that I'd like you to make, while you're at it is about the path of the export of the image.
That was a mistake from me, I should have used relative path. And that's exactly what I'd like to see while you're in this PR (i.e. let's fix it! I saw you change it for a bit so you can get around, but why not making it work for everyone :D)

So TLDR:

 - Replace absolute path to relative path.
 - Ensure the directory in which you'll generate the icons is ignored by git

For the folder name, on the root of the project with something like `generated_icons` would be perfect.

**Comment by greavettey** [comment]
Should be good now!

**Review by louis-bompart — APPROVED** [review]
Perfect! Thanks a lot 🎉

**Comment by louis-bompart** [comment]
@all-contributors please add @axelgreavette for code

**Pull request merged**
